### ISSUE TITLE
Problem: misnamed field in workflow package

### ISSUE THREAD

**Issue by sevein** [artefactual-labs/ccp#6]
The workflow package has [a pair of structs](https://github.com/sevein/ccp/blob/acaeb128038d05fa5258e857fbda3e30f51fb113/hack/ccp/internal/workflow/workflow.go#L227C6-L241) with a misnamed field `ChainID`. It should read `LinkID` instead for clarity. The JSON representation must remain as `chain_id` to maintain compatibility with Archivematica, it's a mistake we made in the past that could be eventually solved in the JSON-encoded representation.

**Comment by repson** [comment]
@sevein Struct WatchedDirectory also has a field called ChainID. Does this field also need to be renamed to LinkID?

**Comment by sevein** [comment]
Nope, watched dirs point to chains.
