### ISSUE TITLE
Problem: logging verbosity can't be configured via env in servercmd

### ISSUE THREAD

**Issue by sevein** [artefactual-labs/ccp#9]
It's probably fine to define root flags like [these](https://github.com/sevein/ccp/blob/acaeb128038d05fa5258e857fbda3e30f51fb113/hack/ccp/internal/rootcmd/cmd.go#L24-L27) so they're available to other subcommands that we implement in the future, but I dont' seem to be able to override the config using the env strings configured in [servercmd/cmd.go](https://github.com/sevein/ccp/blob/ccp/hack/ccp/internal/servercmd/cmd.go). I'd like to be able to configure the verbosity of the logger using an environment string just like any other configuration attribute that it's available.

**Comment by repson** [comment]
@sevein Is there a defined limit to the possible values of verbosity? In order to narrow down the possible values to assign in the environment variable.

**Comment by sevein** [comment]
Not really, but the logr docs recommend staying within the 0-10 range and I don't expect to go beyond that. You could just accept a uint.

https://github.com/go-logr/logr?tab=readme-ov-file#how-do-i-choose-my-v-levels
